

FOLLOW_GOOGLE_LINKS: False
allImages: False

type: "eastern"

baseUrl: [
	"http://www.novelupdates.com",
	]

send_raw_feed: False
trigger: False

badwords: [

			'/more-reviews/',
			'/comment-page-',
			'/readlist/',
			'/extnu/',


			# Apparently it's built on top of wordpress?
			# Wat?
			'/wp-includes/',
			'/fdrev/',
			'/login/',

			'/lostpassword/',
			'/rank-graph/',
			'/feed/',


			# Don't actually spider the site, just let the update triggers
			# do their thing.
			# 'www.novelupdates.com',
			]

# Content Stripping needs to be determined.
decomposeBefore: [

]

decompose: [
]

stripTitle: []


destyle : [
]


preserveAttrs : [
]

special_case_filters : {

	# Apparently they don't like bots. Well, too bad.
	"www.novelupdates.com" : ["rate_limit", 10],
	"novelupdates.com"     : ["rate_limit", 10],

	# So I can test against someone less bot-sensitive
	"www.google.com" : ["rate_limit", 20],
}
