

FOLLOW_GOOGLE_LINKS: False
allImages: False

type: "eastern"

baseUrl: [
	"http://www.novelupdates.com",
	]

send_raw_feed: False
trigger: False

badwords: [
			"/about/",
			"/join-us/",
			"/chat/",
			'&format=pdf',
			'?format=pdf',
			'?replytocom=',
			"/forum/",
			"/forum",
			"/forums/",
			"#comment",
			"/forums",

			"/post.php?",
			"/author.php?",
			'/more-reviews/',
			'/readlist/',
			'/extnu/',
			]

# Content Stripping needs to be determined.
decomposeBefore: [

]

decompose: [
]

stripTitle: []


destyle : [
]


preserveAttrs : [
]

special_case_filters : {

	# Apparently they don't like bots. Well, too bad.
	"www.novelupdates.com" : ["remote_fetch", "WebRequest", "getItem"],
	"novelupdates.com"     : ["remote_fetch", "WebRequest", "getItem"],

	# So I can test against someone less bot-sensitive
	"www.google.com" : ["remote_fetch", "WebRequest", "getItem"],
}
